In [ ]:
# Class Variables:
# Class Variables can be accessed by using the class name and object reference.

class Student:
    name='Gowtham'
    age=23
    loc=None
Student.loc='Hyderabad'
#accessing the class variable
# Using className
print(Student.name,Student.age,Student.loc)
#Using ObjectReference
s1=Student()
print(s1.name,s1.age,s1.loc)

#dict form of class.
print(Student)
print(Student())
print(Student.__dict__)
#dict form of object.
print(s1)
print(s1.__dict__)#__dict__ shows only instance attributes, not the inherited class variables.



# Updating the class varaible:
# Class Variables can be modified/Updated by using the class name and object reference.
# By using class name
Student.name='Krish'
print(Student.name)
# If we use class name then it will change in the main class attribute..

#By using object reference
s1.name='Ajay'
print(s1.name)
s2=Student()
print(s2.name)
# If we use object reference then it will change only in the current object reference.

# Deleting the class Variables..
# Class Variables can be modified/Updated by using the class name only.
#By using class Name
del Student.loc
print(Student.__dict__)

Gowtham 23 Hyderabad
Gowtham 23 Hyderabad
<class '__main__.Student'>
<__main__.Student object at 0x000001CDC4F92930>
{'__module__': '__main__', 'name': 'Gowtham', 'age': 23, 'loc': 'Hyderabad', '__dict__': <attribute '__dict__' of 'Student' objects>, '__weakref__': <attribute '__weakref__' of 'Student' objects>, '__doc__': None}
<__main__.Student object at 0x000001CDC4FD8710>
{}
Krish
Ajay
Krish
{'__module__': '__main__', 'name': 'Krish', 'age': 23, '__dict__': <attribute '__dict__' of 'Student' objects>, '__weakref__': <attribute '__weakref__' of 'Student' objects>, '__doc__': None}

AttributeError: 'Student' object has no attribute 'age'

In [24]:
# Object Variables:
# Object Variables can be created by 
# By converting the class varaibles into object variables.
class Employee:
    name=None
    age=None
e1=Employee()
e1.name='Gowtham'
e1.age=23
print(e1.__dict__)

# By using the current object reference.
class Emp:
    None
e11=Emp()
e11.name='GOWTHAM'
e11.age=23
print(e11.__dict__)


# Accessing the object variables are can be done by using object reference.
print(e1.name)

# Modifying / Updating object variable can be done by using object reference.
e11.name='Uma'
print(e11.__dict__)

# Deleting the object variables can be done by using the object reference..
del e11.age
print(e11.__dict__)

{'name': 'Gowtham', 'age': 23}
{'name': 'GOWTHAM', 'age': 23}
Gowtham
{'name': 'Uma', 'age': 23}
{'name': 'Uma'}

In [ ]:
#create a class mobile.
# create two class variables like mobile brand and colour.
# create two object variables like mobile price and mobile RAM.
# Perform all the CRUD operations with respect to class variables and object variables.

class Mobile:
    brand='Realme'
    colour='Comet White'
    price=None
    RAM=None
print(Mobile.__dict__)
m1=Mobile()
m1.colour='Black'
m1.price=16000
m1.RAM='8GB'
print(m1.brand,m1.colour,m1.price,m1.RAM)
m1.price=18000
print(m1.price)
del m1.RAM
print(m1.__dict__)

{'__module__': '__main__', 'brand': 'Realme', 'colour': 'Comet White', 'price': None, 'RAM': None, '__dict__': <attribute '__dict__' of 'Mobile' objects>, '__weakref__': <attribute '__weakref__' of 'Mobile' objects>, '__doc__': None}
Realme Black 16000 8GB
18000
{'colour': 'Black', 'price': 18000}

In [ ]:
#create a class laptop.
# create three class variables like laptop brand , price,colour.
# create two object variables like RAM, OS
# Perform all the CRUD operations w r t all the class and object variables w r t each object.

class Laptop:
    brand='HP Pavilion'
    price=50000
    colour='Voilet Black'
    RAM=None
    OS=None
print(Laptop.__dict__)
l1=Laptop()
l2=Laptop()
l3=Laptop()
l4=Laptop()
l1.RAM='8GB'
print(l1.RAM)
l2.OS='Android'
print(l2.OS)
l3.brand='HP Notebook'
print(l3.brand)
l4.OS='IOS'
print(l4.OS)
del l4.OS
#print(l4.colour)

{'__module__': '__main__', 'brand': 'HP Pavilion', 'price': 50000, 'colour': 'Voilet Black', 'RAM': None, 'OS': None, '__dict__': <attribute '__dict__' of 'Laptop' objects>, '__weakref__': <attribute '__weakref__' of 'Laptop' objects>, '__doc__': None}
8GB
Android
HP Notebook
IOS

In [1]:
# Object Methods: Inorder to perform some kind of operations on object variables, we require object methods.
# It helps us reduicng the code.. Where we can create object varaibles for multiple objects at a single time
# using methods in the class which are nothing but object methods.

#Creating and reading the object varaibles with the help of object methods.
class School:
    school_name='Sai Vineeth School'
    loc='Pundi'
    def create_details(self,name,age):
        self.student_name=name
        self.student_age=age
    
    def display_student(self):
        return f'{self.student_name},{self.student_age}'
    
student1=School()
student1.create_details('Gowtham',14)
print(student1.display_student())

student2=School()
student2.create_details('Devi',14)
print(student2.display_student())
print(student2.student_name, student2.school_name)

Gowtham,14
Devi,14
Devi Sai Vineeth School

In [ ]:
#WAPFBR
# Create a class company.
# create 5 class variables.
# create 7 object variables.
# create a method for reading the object variables.
# create a method for creating the object variables.
# create 5 objects.

class Company:
    company_name='Jp Morgan'
    headquarters='New York'
    industry_type='Finanical services'
    founded_year=1799
    company_policy='2025.1'
    def emp_details(self, id, name, title, dept, sal, email, years):
        self.emp_id=id
        self.emp_name=name
        self.job_title=title
        self.department=dept
        self.salary=sal
        self.emp_email=email
        self.workedyears=years
    
    def display_empdetails(self):
        return (
                f"Employee ID: {self.emp_id}\n"
                f"Name: {self.emp_name}\n"
                f"Job Title: {self.job_title}\n"
                f"Department: {self.department}\n"
                f"Salary: {self.salary}\n"
                f"Email: {self.emp_email}\n"
                f"Worked Years: {self.workedyears}"
            )

emp1=Company()
emp1.emp_details(
    'JP10235',
    'Sai Kiran',
    'Data Scientist',
    'Cooperate and Investment',
    '20LPA',
    'saikiran@jpmorgan.com',
    3
)
emp2=Company()
emp2.emp_details(
    'JP10412',
    'Priya Sharma',
    'Software Engineer',
    'Retail Banking Technology',
    '12 LPA',
    'priya.sharma@jpmorgan.com',
    4
)
emp3=Company()
emp3.emp_details(
    'JP10876',
    'Rahul Verma',
    'Senior Analyst',
    'Risk and Compliance',
    '15 LPA',
    'rahul.verma@jpmorgan.com',
    6
)
emp4=Company()
emp4.emp_details(
    'JP11023',
    'Ananya Gupta',
    'Business Analyst',
    'Corporate Strategy',
    '14 LPA',
    'ananya.gupta@jpmorgan.com',
    7
)
emp5=Company()
emp5.emp_details(
    'JP11298',
    'Vikram Singh',
    'Cloud Engineer',
    'Infrastructure Services',
    '18 LPA',
    'vikram.singh@jpmorgan.com',
    2
)
emp6=Company()
emp6.emp_details(
    'JP11544',
    'Meena Reddy',
    'UI/UX Designer',
    'Digital Solutions',
    '13 LPA',
    'meena.reddy@jpmorgan.com',
    8
)
emp7=Company()
emp7.emp_details(
    'JP11890',
    'Arun Nair',
    'Project Manager',
    'Corporate Technology',
    '22 LPA',
    'arun.nair@jpmorgan.com',
    9
)
print(emp1.display_empdetails())
print(emp2.display_empdetails())
print(emp3.display_empdetails())
print(emp4.display_empdetails())
print(emp5.display_empdetails())
print(emp6.display_empdetails())
print(emp7.display_empdetails())

Employee ID: JP10235
Name: Sai Kiran
Job Title: Data Scientist
Department: Cooperate and Investment
Salary: 20LPA
Email: saikiran@jpmorgan.com
Worked Years: 3
Employee ID: JP10412
Name: Priya Sharma
Job Title: Software Engineer
Department: Retail Banking Technology
Salary: 12 LPA
Email: priya.sharma@jpmorgan.com
Worked Years: 4
Employee ID: JP10876
Name: Rahul Verma
Job Title: Senior Analyst
Department: Risk and Compliance
Salary: 15 LPA
Email: rahul.verma@jpmorgan.com
Worked Years: 6
Employee ID: JP11023
Name: Ananya Gupta
Job Title: Business Analyst
Department: Corporate Strategy
Salary: 14 LPA
Email: ananya.gupta@jpmorgan.com
Worked Years: 7
Employee ID: JP11298
Name: Vikram Singh
Job Title: Cloud Engineer
Department: Infrastructure Services
Salary: 18 LPA
Email: vikram.singh@jpmorgan.com
Worked Years: 2
Employee ID: JP11544
Name: Meena Reddy
Job Title: UI/UX Designer
Department: Digital Solutions
Salary: 13 LPA
Email: meena.reddy@jpmorgan.com
Worked Years: 8
Employee ID: JP11890
Name: Arun Nair
Job Title: Project Manager
Department: Corporate Technology
Salary: 22 LPA
Email: arun.nair@jpmorgan.com
Worked Years: 9

In [ ]:
class Train:
    railway_zone = "Indian Railways"
    country = "India"
    track_gauge = "Broad Gauge"
    fuel_type = "Electric/Diesel"
    max_speed_limit = 160 
    ticket_booking_system = "IRCTC"
    year_established = 1853


    def train_details(self, train_no, train_name, source, destination, total_coaches, fare, travel_time):
        self.train_no = train_no
        self.train_name = train_name
        self.source = source
        self.destination = destination
        self.total_coaches = total_coaches
        self.fare = fare
        self.travel_time = travel_time


    def display_train_details(self):
        return (
            f"Train Number: {self.train_no}\n"
            f"Train Name: {self.train_name}\n"
            f"Source: {self.source}\n"
            f"Destination: {self.destination}\n"
            f"Total Coaches: {self.total_coaches}\n"
            f"Fare: {self.fare}\n"
            f"Travel Time: {self.travel_time}\n"
            f"Railway Zone: {Train.railway_zone}\n"
            f"Country: {Train.country}\n"
        )


train1 = Train()
train1.train_details(12627, "Karnataka Express", "Bengaluru", "New Delhi", 24, "3,250 (AC 2 Tier)", "36h 30m")

train2 = Train()
train2.train_details(12050, "Gatimaan Express", "Delhi", "Jhansi", 10, "1,500 (AC Chair Car)", "4h 25m")

train3 = Train()
train3.train_details(22691, "Rajdhani Express", "Bengaluru", "Hazrat Nizamuddin", 20, "4,800 (AC 1 Tier)", "33h 00m")


print(train1.display_train_details())
print(train2.display_train_details())
print(train3.display_train_details())

Train Number: 12627
Train Name: Karnataka Express
Source: Bengaluru
Destination: New Delhi
Total Coaches: 24
Fare: 3,250 (AC 2 Tier)
Travel Time: 36h 30m
Railway Zone: Indian Railways
Country: India

Train Number: 12050
Train Name: Gatimaan Express
Source: Delhi
Destination: Jhansi
Total Coaches: 10
Fare: 1,500 (AC Chair Car)
Travel Time: 4h 25m
Railway Zone: Indian Railways
Country: India

Train Number: 22691
Train Name: Rajdhani Express
Source: Bengaluru
Destination: Hazrat Nizamuddin
Total Coaches: 20
Fare: 4,800 (AC 1 Tier)
Travel Time: 33h 00m
Railway Zone: Indian Railways
Country: India

In [ ]:
# Constructor:

class Train:
    railway_zone = "Indian Railways"
    country = "India"
    track_gauge = "Broad Gauge"
    fuel_type = "Electric/Diesel"
    max_speed_limit = 160 
    ticket_booking_system = "IRCTC"
    year_established = 1853


    def __init__(self, train_no, train_name, source, destination, total_coaches, fare, travel_time):
        self.train_no = train_no
        self.train_name = train_name
        self.source = source
        self.destination = destination
        self.total_coaches = total_coaches
        self.fare = fare
        self.travel_time = travel_time


    def display_train_details(self):
        return (
            f"Train Number: {self.train_no}\n"
            f"Train Name: {self.train_name}\n"
            f"Source: {self.source}\n"
            f"Destination: {self.destination}\n"
            f"Total Coaches: {self.total_coaches}\n"
            f"Fare: {self.fare}\n"
            f"Travel Time: {self.travel_time}\n"
            f"Railway Zone: {Train.railway_zone}\n"
            f"Country: {Train.country}\n"
        )

train1 = Train(12627, "Karnataka Express", "Bengaluru", "New Delhi", 24, "3,250 (AC 2 Tier)", "36h 30m")

train2 = Train(12050, "Gatimaan Express", "Delhi", "Jhansi", 10, "1,500 (AC Chair Car)", "4h 25m")

train3 = Train(22691, "Rajdhani Express", "Bengaluru", "Hazrat Nizamuddin", 20, "4,800 (AC 1 Tier)", "33h 00m")

print(train1.display_train_details()) 
print(train2.display_train_details())
print(train3.display_train_details())

Train Number: 12627
Train Name: Karnataka Express
Source: Bengaluru
Destination: New Delhi
Total Coaches: 24
Fare: 3,250 (AC 2 Tier)
Travel Time: 36h 30m
Railway Zone: Indian Railways
Country: India

Train Number: 12050
Train Name: Gatimaan Express
Source: Delhi
Destination: Jhansi
Total Coaches: 10
Fare: 1,500 (AC Chair Car)
Travel Time: 4h 25m
Railway Zone: Indian Railways
Country: India

Train Number: 22691
Train Name: Rajdhani Express
Source: Bengaluru
Destination: Hazrat Nizamuddin
Total Coaches: 20
Fare: 4,800 (AC 1 Tier)
Travel Time: 33h 00m
Railway Zone: Indian Railways
Country: India

In [7]:
class Train:
    def __init__(self,name,age,gender):
        self.name=name
        self.age=age
        self.gender=gender
    def __str__(self):
        return f'{self.name} --> {self.age}'
p1=Train('raghu',21,'male')
print(p1)

raghu --> 21

In [10]:
class College:
    clg_name='Aditya College of Engineering and Technology'
    clg_code='ACET'
    clg_adrs='Surampalem'
    
    def __init__(self,name,age,degree,stream,gender):
        self.name=name
        self.age=age
        self.degree=degree
        self.stream=stream
        self.gender=gender
    
    def __str__(self):
        return f'{self.name}{self.age}{self.degree[:2]}{self.stream}{self.gender[0]}@gmail.com'
    
s1=College('Ramu',21,'BTech','CSE','Male')
print(s1)
s2=College('Uma',21,'Bsc','CS','Male')
print(s2)
s3=College('Rani',20,'BTech','ECE','Female')
print(s3)
s4=College('Ramesh',21,'BTech','MECH','Male')
print(s4)
s5=College('Ramani',20,'BTech','AIML','Female')
print(s5)

Ramu21BTCSEM@gmail.com
Uma21BsCSM@gmail.com
Rani20BTECEF@gmail.com
Ramesh21BTMECHM@gmail.com
Ramani20BTAIMLF@gmail.com

In [7]:
class School:
    scl_name='Sai Vineeth School'
    scl_code='SVP'
    scl_adrs='Pundi'
    
    def __init__(self,name,age,gender,_class,section):
        self.name=name
        self.age=age
        self.gender=gender
        self._class=_class
        self.section=section
    
    def __str__(self):
        return f'{self.name}, {self.age}, {self.gender}, {self._class}, {self.section}'
    
    def change_name(self,nname):
        self.name=nname
    
    def change_details(self,nname=None,nage=None,ngender=None,n_class=None,nsection=None):
        if nname is not None:
            self.name=nname
        if nage is not None:
            self.age=nage
        if ngender is not None:
            self.gender=ngender
        if n_class is not None:
            self._class=n_class
        if nsection is not None:
            self.section=nsection
    
    def delete_name(self):
        del self.name

s1=School('Ramu',14,'Male','10','A')
print(s1)
s1.change_name('Gowtham')
print(s1)
s1.change_details(nage=16)
print(s1)
s1.delete_name()

Ramu, 14, Male, 10, A
Gowtham, 14, Male, 10, A
Gowtham, 16, Male, 10, A

In [17]:
# Class methods: Peforming crud opeartions on class variables.
class Mobile:
    os='Andriod'
    sim_slots=2
    display='OLED'

    def __init__(self,m_name,camera,price):
        self.m_name=m_name
        self.camera=camera
        self.price=price

    def __str__(self):
        return f'{self.m_name} : {self.camera} : {self.price}'
    
    @classmethod
    def view_clsv_details(cls):
        return f'{cls.os}--{cls.sim_slots}--{cls.display}'
    
    @classmethod
    def create_clsv(cls,crgtype):
        cls.charger_type=crgtype
    
    @classmethod
    def read_clsv(cls):
        return f'{cls.charger_type}'
    
    @classmethod
    def update_os(cls,new_os):
        cls.os=new_os

    @classmethod
    def delete_simslots(cls):
        del cls.sim_slots

mobile1=Mobile('Realme 6','64mp',16000)
print(mobile1)

print(mobile1.view_clsv_details())

mobile1.create_clsv('C-Type')
print(mobile1.read_clsv())

mobile1.update_os('Andriod 16')
print(mobile1.view_clsv_details())

mobile1.delete_simslots()
#print(mobile1.view_clsv_details())

Realme 6 : 64mp : 16000
Andriod--2--OLED
C-Type
Andriod 16--2--OLED

In [ ]:
#Create a class Restuarant
#Create 5 class Variables.
#Create 5 object variables
#create a class method to modify anyone of the class variable.
#create a class method to add 2 class varaibles.

class Restuarant:
    Resto_name='Paradise'
    Resto_adrs='Palasa'
    Resto_branches=5
    Resto_owner='Gowtham'
    Resto_tag='Never disappoints U'

    def __init__(self,biryani,starters,drinks,waterbottle,riceitem):
        self.biryani=biryani
        self.starters=starters
        self.drinks=drinks
        self.waterbottle=waterbottle
        self.riceitem=riceitem

    def __str__(self):
        return f'{self.biryani} {self.starters} {self.drinks} {self.waterbottle} {self.riceitem}'
        
    @classmethod
    def display_clsv_details(cls):
        return f'{cls.Resto_name}--{cls.Resto_adrs}--{cls.Resto_branches}--{cls.Resto_owner}--{cls.Resto_tag}'

    @classmethod
    def change_owner_name(cls,nowner):
        cls.Resto_owner=nowner

    @classmethod
    def create_2clsv(cls,famous_for,rating):
        cls.Resto_famousFor=famous_for
        cls.Resto_rating=rating

    @classmethod
    def read_updatedclsv(cls):
        return f'{cls.Resto_famousFor}--{cls.Resto_rating}'
    
order1=Restuarant('Dum Birayni','Chicken Lollipop','Sprite',1,'CurdRice')
print(order1)

print(order1.display_clsv_details())

order1.change_owner_name('UMA Venkat')
print(order1.display_clsv_details())

order1.create_2clsv('Hyderbad Dum ki Biryani','*****')
print(order1.read_updatedclsv())

Dum Birayni Chicken Lollipop Sprite 1 CurdRice
Paradise--Palasa--5--Gowtham--Never disappoints U
Paradise--Palasa--5--UMA Venkat--Never disappoints U
<bound method Restuarant.read_updatedclsv of <class '__main__.Restuarant'>>

In [ ]:
class Bank:
    b_name='SBI'
    branch='Nandigam'
    IFSC_code='SBIN0016958'

    def __init__(self,ac_holder,ac_no,age,pin,balance=0):
        self.ac_holder=ac_holder
        self.ac_no=ac_no
        self.age=age
        self.pin=pin
        self.balance=balance

    def __str__(self):
        return f'{self.ac_holder}->{self.ac_no}'
    
    @classmethod
    def add_branch_manager(cls,manager):
        cls.manager=manager
    
    def holder_details(self):
        print('--------User Info--------')
        pin=int(input('Enter Your Pin:'))
        if pin==self.pin:
            return f'''Welcome to {Bank.b_name} Bank.. Hello {self.ac_holder} with accno of {self.ac_no}
and a balance of {self.balance}. Thank You.....'''
        return f'Enter the valid pin'
    
    def deposit(self):
        print('------Deposit Amount-------')
        pin=int(input('Enter Your Pin:'))
        if pin==self.pin:
            deposit_amount=int(input('Enter deposit amount:'))
            if deposit_amount>0:
                self.balance+=deposit_amount
                return f'''Amount deposited to accno {self.ac_no} with deposit amount of {deposit_amount}
and current balance is {self.balance}'''
            else:
                return 'Enter Valid deposit amount(>0)'
        print('Enter valid pin')
        return self.deposit()  

    def withdrawal(self):
        print('------Withdraw Amount-------')
        pin=int(input('Enter Your Pin:'))
        if pin==self.pin:
            withdrawal_amount=int(input('Enter withdrawal amount:'))
            if withdrawal_amount>self.balance:
                self.balance-=withdrawal_amount
                return f'''Amount withdrawn from accno {self.ac_no} with withdrawal amount of {withdrawal_amount}
and current balance is {self.balance}'''
            else:
                return 'Enter Valid deposit amount(>0)'
        print('Enter valid pin')
        return self.withdrawal()

cus1=Bank('Gowtham Jami','20448771736',23,2025)
print(cus1)
print(cus1.holder_details())
print(cus1.deposit())
print(cus1.withdrawal())

Gowtham Jami->20448771736

Welcome to SBI Bank.. Hello Gowtham Jami with accno of 20448771736
and a balance of 0. Thank You.....
Amount deposited to accno 20448771736 with deposit amount of 20000
and current balance is 20000
Amount withdrawn from accno 20448771736 with withdrawal amount of 10000
and current balance is 10000